### ISSUE TITLE
Git hook does not send the full commit message to eventum

### ISSUE THREAD

**Issue by rjroos** [eventum/scm#2]
The eventum-git-hook.php does not find issues on line 3 in a commit message.

So when committing with this message: "
Improve lots of things

Long explanation

Issue: #12"

It will not find issue 12.

This  patch solves that.
[full-commit-message.patch.txt](https://github.com/eventum/scm/files/340721/full-commit-message.patch.txt)

**Comment by glensc** [comment]
sorry, did not notice this earlier, notifications were off for this project
